// Copyright (c) 2019 shitaro2016
// 
// This software is released under the MIT License.
// https://opensource.org/licenses/MIT

import React from "react";
import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Typography from "@material-ui/core/Typography";
import Container from "@material-ui/core/Container";
import MediaCard from "../components/MediaCard";
import articleMetaList from "../utils/ArticleMetaList";

const IndexPage: NextPage = () => {
  articleMetaList.sort((a,b) => {
    const keyA = Object.keys(a)[0];
    const keyB = Object.keys(b)[0];
    return (
      a[keyA].title < b[keyB].title ? 1 : -1
    )
  });

  return (
    <>
      <Head>
        <title>幸福の物理 - Haphysics</title>
      </Head>
      <Container maxWidth="md">
        <Typography component="h1" variant="h2" gutterBottom>
          Welcom to Haphysics!
        </Typography>
        <Typography component="body" variant="body1" gutterBottom>
          <p>ようこそ、幸福の物理へ。</p>
          <p>This website is under construction now...</p>
          <p>This website is generated by <Link href="https://github.com/Shitaro/haphysics-pages"><a>this source code</a></Link>!</p>
        </Typography>
        <Typography component="h2" variant="h2" gutterBottom>
          Article List
        </Typography>
        {articleMetaList.map(articleMeta => {
          const article = Object.keys(articleMeta)[0];
          return (
            <>
              <MediaCard
                article={article}
                title={articleMeta[article].title}
                thumbnail={articleMeta[article].thumbnail}
                description={articleMeta[article].description}
                categoryList={articleMeta[article].categoryList}
              />
              <p />
            </>
          )
        })}
      </Container>
    </>
  )
};

export default IndexPage;